### ISSUE TITLE
Scaneinheiten bestellen

### ISSUE THREAD

**Issue by niccokunzmann** [fablabcb/openbookscanner#5]
Carsten und ich machen ja beim Scannen was.
Die Scanner sind noch nicht bestellt.
Ich würde das gerne machen. Die eingetragene Liste aus dem Wiki
http://www.sane-project.org/cgi-bin/driver.pl?manu=&model=&bus=usb&v=&p=
ist riesig.

**Woher kommt die Idee, dass wir Canon-Scaneinheiten brauchen? In der Liste geht vieles andere.**

Nun habe ich die Sorge, wenn ich jetzt eines bestelle, ist es das Falsche, hat nicht die Größe oder kann nicht dort angeschraubt werden,
wo es angeschraubt werden sollte.

Frage: **Habt ihr weitere Hinweise, welches Modul genau gebraucht wird?**
Da es recht offen sein soll, denke ich, dass wir eigendlich alles nehmen können.
Gibt es Größenbeschränkungen? A3-Format (30cm)/A4-Format(20cm)?

**Comment by carsifreifunk** [comment]
In der Dokumentation wurde von einer Canon Scaneinheit geschrieben. 
Außerdem ist der CanoScan LiDE einer der günstigsten Flachbettscanner, die für relativ wenig Geld und einfach zu beschaffen ist. Daher war ich jetzt mit dem Scanner vorgeprescht. Wenn du eine bessere ALternative hast, her damit.

**Comment by niccokunzmann** [comment]
Eine Scaneinheit habe ich aus der machBar mitgenommen und habe ein Bild gescannt.

**Comment by niccokunzmann** [comment]
Jetzt verwenden wir erstmal die Camera-App #11
